name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y libjpeg-dev zlib1g-dev libpq-dev build-essential

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: "myproject.settings"
      run: |
        python manage.py test
